before_script:
  - 'npm -v'
  - node -v

stages:
  - install_deps
  - test
  - prod

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

job-install_deps:
  stage: install_deps
  only:
    - test
  tags:
    - frontend-runner
  script:
    - npm install

job-deploy-test:
  stage: test
  only:
    - test
  tags:
    - frontend-runner
  script:
    - 'time npm run box'
    - 'npm run cptotest'

job-deploy-prod:
  stage: prod
  only:
    - master
  except:
    - tags
  tags:
    - frontend-runner
  script:
    - 'npm -v'